from __future__ import annotations

from enum import StrEnum


class WorkflowStatus(StrEnum):
    CREATED = "CREATED"
    QUESTION_RECEIVED = "QUESTION_RECEIVED"
    CLARIFYING = "CLARIFYING"
    READY_FOR_DRAW = "READY_FOR_DRAW"
    DRAW_COMPLETED = "DRAW_COMPLETED"
    SYNTHESIS_COMPLETED = "SYNTHESIS_COMPLETED"
    SAFETY_REVIEWED = "SAFETY_REVIEWED"
    COMPLETED = "COMPLETED"
    SAFE_FALLBACK_RETURNED = "SAFE_FALLBACK_RETURNED"
    FAILED = "FAILED"
